{
    'name': 'WKK - Approvals',
    'summary': 'WKK Approvals Extension',
    'author': 'Odoo PS',
    'license': 'OEEL-1',
    'website': 'https://www.odoo.com',
    'category': 'Human Resources/Approvals',
    'version': '19.0.2.1.0',
    'depends': ['approvals', 'accountant', 'purchase_requisition', 'documents', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/account_move_views.xml',
        'views/approval_category_views.xml',
        "views/model_approval_settings_views.xml",
        'views/approval_request_views.xml',
        "views/approval_product_line_views.xml",
        "views/approval_category_approver_views.xml",
        'views/documents_type_views.xml',
        'views/purchase_order_views.xml',
        'views/purchase_requisition_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/account_menu_items.xml',
        'views/sale_order_views.xml',
    ],
    'task_ids': [5122426, 5211287]
}
