from . import hr_insurance_provider
from . import hr_insurance_category
from . import hr_insurance_allocation
from . import hr_dependent_relation
from . import hr_dependent_dependent
from . import hr_employee
from . import hr_employee_public
from . import hr_job
from . import hr_version
from . import approval_category
from . import hr_leave_type
from . import hr_leave
from . import approval_request
